### ISSUE TITLE
add More function 

### ISSUE THREAD

**Issue by bashon1** [ali-exacute/esx_adminplus#10]
Hello
your script help me to much on final version of es_extended
if possible add more function on it like
revive player by range for example revive ID from 10  to 20
/reviveR 10 20
and bring all players

**Comment by ali-exacute** [comment]
hello
i am not sure there is already a plug-in for these commands or not, but if i got any time to work on this resource again, i will add some new commands.
right now i am dealing with my project and IRL stuff...
(BTW , you can send pull request if you did something cool and want to share!)
