### ISSUE TITLE
say command

### ISSUE THREAD

**Issue by ismaelviac** [ali-exacute/esx_adminplus#3]
whe use say command in console console print this 

print ^1SERVER Announcement ^0:y h

dont find this y on lua files

**Comment by ali-exacute** [comment]
can you provide an screenshot ?

**Comment by ismaelviac** [comment]
[91mSERVER Announcement [97m: y hola

![2](https://user-images.githubusercontent.com/59666577/89993833-98c58a80-dc87-11ea-97a4-056f09a944f8.png)
![1](https://user-images.githubusercontent.com/59666577/89993838-9bc07b00-dc87-11ea-9596-d515b00c0e1f.png)

**Comment by ali-exacute** [comment]
I am not sure what panel is this but that is not my script problem and your panel just print it like that
If it is fine for clients, its not a problem

**Comment by ismaelviac** [comment]
i fixed it 
server.lua line 95
change 
local message = string.sub(rawCommand, 4)
with
local message = string.sub(rawCommand, 5)


I'm using open game panel
