### ISSUE TITLE
Using any command throws an error

### ISSUE THREAD

**Issue by crypticcfrost** [ali-exacute/esx_adminplus#4]
I,.a couple of hours back installed this resource since this is an amazing peice of work. I really wanted this into my server but unfortunately using any command throws an error in the console and the chat box. I have replied on your FiveM forum post too with all the information, please fix it since it is impossible to find such an amazing resource.

**Comment by ali-exacute** [comment]
Thank you for telling me about it , i will fix it ASAP, and please send a screenshot of error

**Comment by crypticcfrost** [comment]
Thank you for your response! Just observed a few commands like /announce work. But when I try /noclip, /admin, /tpm .. It throws out the error I have attached below.
![image](https://user-images.githubusercontent.com/63742049/92470377-edf7ac00-f1f3-11ea-9b38-dac15f25c985.png)
![image](https://user-images.githubusercontent.com/63742049/92470406-fbad3180-f1f3-11ea-8df2-e29770797cdd.png)

**Comment by ali-exacute** [comment]
> 
> 
> Thank you for your response! Just observed a few commands like /announce work. But when I try /noclip, /admin, /tpm .. It throws out the error I have attached below.
> ![image](https://user-images.githubusercontent.com/63742049/92470377-edf7ac00-f1f3-11ea-9b38-dac15f25c985.png)
> ![image](https://user-images.githubusercontent.com/63742049/92470406-fbad3180-f1f3-11ea-8df2-e29770797cdd.png)

try changing `xPlayer.playerId` to `xPlayer.source` and tell me about the result
i cant test myself rn..

**Comment by crypticcfrost** [comment]
Dude you are the best man! I replaced all the xPlayer.playerId in the server file to xPlayer.source and everything works like a charm! Just let me know if you want me to make a pull request so it is updated on the GitHub too ... There are a few people in the FiveM forum seeking help too :)

**Comment by ali-exacute** [comment]
> 
> 
> Dude you are the best man! I replaced all the xPlayer.playerId in the server file to xPlayer.source and everything works like a charm! Just let me know if you want me to make a pull request so it is updated on the GitHub too ... There are a few people in the FiveM forum seeking help too :)

i would appreciate that if you open a pull request :)
also dont forget to change `xTarget.playerId` to `xTarget.source` aswell

**Comment by crypticcfrost** [comment]
Have made all the required changes and made a pull request! Thanks a lot for your quick response and support! Much appreciated :) If anything else, feel free to throw a DM - **Illumiinati#6536** ( Discord )
