### ISSUE TITLE
No errors but not works

### ISSUE THREAD

**Issue by Bulle93230** [ali-exacute/esx_adminplus#7]
Hi first thanks for your script, i know it works (i tried with es_extended 2.0) but i'm now on es_extended 1.2 and i have 2 issues.
(I use essentialmode too)

1) When i use a command it said **attempt to call a nil value (field 'triggerEvent')** it's for the chat, so i tried to turn these lines into comments ( **--** )

2) When the server stop show the error attempt... it's just does nothing... The commands does really does nothing, and there's no error
When i use goto for exemple or bring, just nothing append.

Do you have an idea for this issue ? please

![adminplus](https://user-images.githubusercontent.com/58170300/93142002-7ccd6280-f6e5-11ea-8c72-4511fe53473f.JPG)

Thanks :)

**Comment by ali-exacute** [comment]
Try the latest version and it will fix this problem

**Comment by Bulle93230** [comment]
Thanks, it's works but now i have a 2 issues now

-And my problems now are **when i use the commands for teleport (/bring /goto /bringback /goback) i have the message in the chat (you have been teleported...) but does nothing
I have no errors for this...

-For the command /a i have the error index a nil value global xTarget
![Capture](https://user-images.githubusercontent.com/58170300/93280183-49fc9a80-f7c9-11ea-8cf6-9e0f7cd1defc.JPG)

(I didn't change anything in the script for now but i send you the script and the error.

Thanks for your help :)

**Comment by Bulle93230** [comment]
Know you why ? please

**Comment by Bulle93230** [comment]
Thanks
