### ISSUE TITLE
/bring /goto /bringback /goback does nothing

### ISSUE THREAD

**Issue by Bulle93230** [ali-exacute/esx_adminplus#8]
[Issue]:
Compatibility with esx (solved)

Hi, i have a 2 issues

-And my problems now are **when i use the commands for teleport (/bring /goto /bringback /goback) i have the message in the chat (you have been teleported...) **but does nothing**
**I have no errors for this**...

-For the command /a i have an error index a nil value global xTarget
![Capture](https://user-images.githubusercontent.com/58170300/93662346-c01a2f00-fa5f-11ea-8fe5-c49c6ae26c9d.JPG)

(I didn't change anything in the script for now but i send you the script and the error.

Thanks for your help :)

**Comment by ali-exacute** [comment]
try the update and tell me if its fixed ( i didnt test it )

**Comment by Bulle93230** [comment]
It's still don't work with the latest version :x
I change fxmanifest.lua into __resource.lua because i had a problem (with fxmanifest)

But when i use /goto /bring.. it write in the chat you have been TP... but does nothing

**Comment by ali-exacute** [comment]
Fxmanifest isnt the problem, and if you didnt update your server to the latest artifact, please do it first

**Comment by Bulle93230** [comment]
Hey, i updated the artifact and for /a it's work, but for /goto, /bring, /gotoback, /bringback, it's still don't work.
It's send the message in the chat You have been teleported to... but it don't teleport me to the people or the people to me...
EDIT: I didn't saw it, when i use **/coords**, it's show me **vector3(0,0,0)**

If you have another idea please, thank you :)

**Comment by Bulle93230** [comment]
I still have the issue.. :x
